export const animals = [
  { name: 'Dog', emoji: '🐶', color: '#ffbf69', phrase: 'The dog says WOOF!', sound: 'woof', fact: 'Dogs love to play and are great animal friends.', habitat: 'Homes and farms' },
  { name: 'Cat', emoji: '🐱', color: '#f8a5c2', phrase: 'The cat says MEOW!', sound: 'meow', fact: 'Cats use their whiskers to help explore the world.', habitat: 'Homes and farms' },
  { name: 'Cow', emoji: '🐮', color: '#9bdeac', phrase: 'The cow says MOO!', sound: 'moo', fact: 'Cows live on farms and eat grass.', habitat: 'Farm' },
  { name: 'Pig', emoji: '🐷', color: '#f6a6bd', phrase: 'The pig says OINK!', sound: 'oink', fact: 'Pigs are smart animals that love exploring.', habitat: 'Farm' },
  { name: 'Sheep', emoji: '🐑', color: '#c8b6ff', phrase: 'The sheep says BAA!', sound: 'baa', fact: 'Sheep grow soft wool that can be used for clothing.', habitat: 'Farm' },
  { name: 'Horse', emoji: '🐴', color: '#f7c59f', phrase: 'The horse says NEIGH!', sound: 'neigh', fact: 'Horses can run fast and have strong legs.', habitat: 'Farm' },
  { name: 'Chicken', emoji: '🐔', color: '#ffe66d', phrase: 'The chicken says CLUCK!', sound: 'cluck', fact: 'Chickens have feathers and lay eggs.', habitat: 'Farm' },
  { name: 'Duck', emoji: '🦆', color: '#85d7ff', phrase: 'The duck says QUACK!', sound: 'quack', fact: 'Ducks have webbed feet that help them swim.', habitat: 'Pond' },
  { name: 'Lion', emoji: '🦁', color: '#ffd166', phrase: 'The lion says ROAR!', sound: 'roar', fact: 'Lions live in groups called prides.', habitat: 'Grassland' },
  { name: 'Elephant', emoji: '🐘', color: '#b9c6d9', phrase: 'The elephant says TRUMPET!', sound: 'trumpet', fact: 'Elephants use their long trunks to reach food and water.', habitat: 'Savanna' },
  { name: 'Monkey', emoji: '🐵', color: '#d4a373', phrase: 'The monkey says OOH OOH!', sound: 'ooh', fact: 'Many monkeys use their hands and tails to climb.', habitat: 'Jungle' },
  { name: 'Frog', emoji: '🐸', color: '#9ee493', phrase: 'The frog says RIBBIT!', sound: 'ribbit', fact: 'Frogs can jump and many live near water.', habitat: 'Pond' },
  { name: 'Bear', emoji: '🐻', color: '#d9b08c', phrase: 'The bear says GRR!', sound: 'grr', fact: 'Bears have strong paws and excellent noses.', habitat: 'Forest' },
  { name: 'Fox', emoji: '🦊', color: '#ffb36b', phrase: 'The fox says YIP!', sound: 'yip', fact: 'Foxes use sharp ears to find small animals.', habitat: 'Forest' },
  { name: 'Rabbit', emoji: '🐰', color: '#e8d7ff', phrase: 'The rabbit says SQUEAK!', sound: 'squeak', fact: 'Rabbits have powerful back legs for hopping.', habitat: 'Meadow' },
  { name: 'Penguin', emoji: '🐧', color: '#cfe8ff', phrase: 'The penguin says HONK!', sound: 'honk', fact: 'Penguins are birds that cannot fly but can swim.', habitat: 'Antarctica' },
  { name: 'Giraffe', emoji: '🦒', color: '#ffe29a', phrase: 'The giraffe says HUM!', sound: 'hum', fact: 'Giraffes have very long necks for reaching leaves.', habitat: 'Savanna' },
  { name: 'Zebra', emoji: '🦓', color: '#e9edf5', phrase: 'The zebra says NEIGH!', sound: 'neigh', fact: 'Every zebra has a unique stripe pattern.', habitat: 'Grassland' },
  { name: 'Panda', emoji: '🐼', color: '#d8f3dc', phrase: 'The panda says HUFF!', sound: 'huff', fact: 'Giant pandas spend lots of time eating bamboo.', habitat: 'Mountain forest' },
  { name: 'Koala', emoji: '🐨', color: '#d7e3ef', phrase: 'The koala says GRUNT!', sound: 'grunt', fact: 'Koalas spend much of their time resting in trees.', habitat: 'Eucalyptus forest' },
  { name: 'Owl', emoji: '🦉', color: '#d9d2ff', phrase: 'The owl says HOOT!', sound: 'hoot', fact: 'Owls have excellent hearing and can turn their heads far.', habitat: 'Forest' },
  { name: 'Dolphin', emoji: '🐬', color: '#a8e6ff', phrase: 'The dolphin says CLICK!', sound: 'click', fact: 'Dolphins are clever swimmers that communicate with sounds.', habitat: 'Ocean' },
  { name: 'Turtle', emoji: '🐢', color: '#b7e4c7', phrase: 'The turtle says HELLO!', sound: 'hello', fact: 'A turtle carries its protective shell wherever it goes.', habitat: 'Land and water' },
  { name: 'Bee', emoji: '🐝', color: '#ffe082', phrase: 'The bee says BUZZ!', sound: 'buzz', fact: 'Bees visit flowers and help pollinate plants.', habitat: 'Garden' }
];
